/* The following code was generated by JFlex 1.4_pre3 on 1/20/19 8:32 PM */

package petter.simplec;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import petter.utils.AnnotatingSymbolFactory.ExtendedLocation;
import petter.utils.Terminal;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_pre3
 * on 1/20/19 8:32 PM from the specification file
 * <tt>file:/home/ckjaer/tum/optimization/project/simpleC/simplec/jflex/Scanner.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String yycmap_packed = 
    "\11\2\1\11\1\5\1\0\1\11\1\10\16\2\4\0\1\11\1\66"+
    "\1\41\1\44\1\1\1\0\1\62\1\0\1\47\1\50\1\4\1\57"+
    "\1\43\1\61\1\54\1\3\1\6\11\7\1\56\1\53\1\65\1\60"+
    "\1\64\1\55\1\0\13\1\1\40\16\1\1\51\1\42\1\52\1\0"+
    "\1\1\1\0\1\17\1\24\1\15\1\21\1\26\1\27\1\30\1\16"+
    "\1\12\1\1\1\33\1\25\1\36\1\13\1\22\1\35\1\1\1\20"+
    "\1\31\1\14\1\23\1\32\1\34\1\1\1\37\1\1\1\45\1\63"+
    "\1\46\1\0\41\2\2\0\4\1\4\0\1\1\2\0\1\2\7\0"+
    "\1\1\4\0\1\1\5\0\27\1\1\0\37\1\1\0\u01ca\1\4\0"+
    "\14\1\16\0\5\1\7\0\1\1\1\0\1\1\21\0\160\2\5\1"+
    "\1\0\2\1\2\0\4\1\10\0\1\1\1\0\3\1\1\0\1\1"+
    "\1\0\24\1\1\0\123\1\1\0\213\1\1\0\5\2\2\0\236\1"+
    "\11\0\46\1\2\0\1\1\7\0\47\1\7\0\1\1\1\0\55\2"+
    "\1\0\1\2\1\0\2\2\1\0\2\2\1\0\1\2\10\0\33\1"+
    "\5\0\3\1\15\0\5\2\6\0\1\1\4\0\13\2\5\0\53\1"+
    "\37\2\4\0\2\1\1\2\143\1\1\0\1\1\10\2\1\0\6\2"+
    "\2\1\2\2\1\0\4\2\2\1\12\2\3\1\2\0\1\1\17\0"+
    "\1\2\1\1\1\2\36\1\33\2\2\0\131\1\13\2\1\1\16\0"+
    "\12\2\41\1\11\2\2\1\4\0\1\1\5\0\26\1\4\2\1\1"+
    "\11\2\1\1\3\2\1\1\5\2\22\0\31\1\3\2\104\0\1\1"+
    "\1\0\13\1\67\0\33\2\1\0\4\2\66\1\3\2\1\1\22\2"+
    "\1\1\7\2\12\1\2\2\2\0\12\2\1\0\7\1\1\0\7\1"+
    "\1\0\3\2\1\0\10\1\2\0\2\1\2\0\26\1\1\0\7\1"+
    "\1\0\1\1\3\0\4\1\2\0\1\2\1\1\7\2\2\0\2\2"+
    "\2\0\3\2\1\1\10\0\1\2\4\0\2\1\1\0\3\1\2\2"+
    "\2\0\12\2\4\1\7\0\1\1\5\0\3\2\1\0\6\1\4\0"+
    "\2\1\2\0\26\1\1\0\7\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\2\0\1\2\1\0\5\2\4\0\2\2\2\0\3\2\3\0"+
    "\1\2\7\0\4\1\1\0\1\1\7\0\14\2\3\1\1\2\13\0"+
    "\3\2\1\0\11\1\1\0\3\1\1\0\26\1\1\0\7\1\1\0"+
    "\2\1\1\0\5\1\2\0\1\2\1\1\10\2\1\0\3\2\1\0"+
    "\3\2\2\0\1\1\17\0\2\1\2\2\2\0\12\2\1\0\1\1"+
    "\17\0\3\2\1\0\10\1\2\0\2\1\2\0\26\1\1\0\7\1"+
    "\1\0\2\1\1\0\5\1\2\0\1\2\1\1\7\2\2\0\2\2"+
    "\2\0\3\2\10\0\2\2\4\0\2\1\1\0\3\1\2\2\2\0"+
    "\12\2\1\0\1\1\20\0\1\2\1\1\1\0\6\1\3\0\3\1"+
    "\1\0\4\1\3\0\2\1\1\0\1\1\1\0\2\1\3\0\2\1"+
    "\3\0\3\1\3\0\14\1\4\0\5\2\3\0\3\2\1\0\4\2"+
    "\2\0\1\1\6\0\1\2\16\0\12\2\11\0\1\1\7\0\3\2"+
    "\1\0\10\1\1\0\3\1\1\0\27\1\1\0\12\1\1\0\5\1"+
    "\3\0\1\1\7\2\1\0\3\2\1\0\4\2\7\0\2\2\1\0"+
    "\2\1\6\0\2\1\2\2\2\0\12\2\22\0\2\2\1\0\10\1"+
    "\1\0\3\1\1\0\27\1\1\0\12\1\1\0\5\1\2\0\1\2"+
    "\1\1\7\2\1\0\3\2\1\0\4\2\7\0\2\2\7\0\1\1"+
    "\1\0\2\1\2\2\2\0\12\2\1\0\2\1\17\0\2\2\1\0"+
    "\10\1\1\0\3\1\1\0\51\1\2\0\1\1\7\2\1\0\3\2"+
    "\1\0\4\2\1\1\10\0\1\2\10\0\2\1\2\2\2\0\12\2"+
    "\12\0\6\1\2\0\2\2\1\0\22\1\3\0\30\1\1\0\11\1"+
    "\1\0\1\1\2\0\7\1\3\0\1\2\4\0\6\2\1\0\1\2"+
    "\1\0\10\2\22\0\2\2\15\0\60\1\1\2\2\1\7\2\4\0"+
    "\10\1\10\2\1\0\12\2\47\0\2\1\1\0\1\1\2\0\2\1"+
    "\1\0\1\1\2\0\1\1\6\0\4\1\1\0\7\1\1\0\3\1"+
    "\1\0\1\1\1\0\1\1\2\0\2\1\1\0\4\1\1\2\2\1"+
    "\6\2\1\0\2\2\1\1\2\0\5\1\1\0\1\1\1\0\6\2"+
    "\2\0\12\2\2\0\4\1\40\0\1\1\27\0\2\2\6\0\12\2"+
    "\13\0\1\2\1\0\1\2\1\0\1\2\4\0\2\2\10\1\1\0"+
    "\44\1\4\0\24\2\1\0\2\2\5\1\13\2\1\0\44\2\11\0"+
    "\1\2\71\0\53\1\24\2\1\1\12\2\6\0\6\1\4\2\4\1"+
    "\3\2\1\1\3\2\2\1\7\2\3\1\4\2\15\1\14\2\1\1"+
    "\17\2\2\0\46\1\1\0\1\1\5\0\1\1\2\0\53\1\1\0"+
    "\u014d\1\1\0\4\1\2\0\7\1\1\0\1\1\1\0\4\1\2\0"+
    "\51\1\1\0\4\1\2\0\41\1\1\0\4\1\2\0\7\1\1\0"+
    "\1\1\1\0\4\1\2\0\17\1\1\0\71\1\1\0\4\1\2\0"+
    "\103\1\2\0\3\2\40\0\20\1\20\0\125\1\14\0\u026c\1\2\0"+
    "\21\1\1\0\32\1\5\0\113\1\3\0\3\1\17\0\15\1\1\0"+
    "\4\1\3\2\13\0\22\1\3\2\13\0\22\1\2\2\14\0\15\1"+
    "\1\0\3\1\1\0\2\2\14\0\64\1\40\2\3\0\1\1\3\0"+
    "\2\1\1\2\2\0\12\2\41\0\3\2\2\0\12\2\6\0\130\1"+
    "\10\0\51\1\1\2\1\1\5\0\106\1\12\0\35\1\3\0\14\2"+
    "\4\0\14\2\12\0\12\2\36\1\2\0\5\1\13\0\54\1\4\0"+
    "\21\2\7\1\2\2\6\0\12\2\46\0\27\1\5\2\4\0\65\1"+
    "\12\2\1\0\35\2\2\0\13\2\6\0\12\2\15\0\1\1\130\0"+
    "\5\2\57\1\21\2\7\1\4\0\12\2\21\0\11\2\14\0\3\2"+
    "\36\1\15\2\2\1\12\2\54\1\16\2\14\0\44\1\24\2\10\0"+
    "\12\2\3\0\3\1\12\2\44\1\122\0\3\2\1\0\25\2\4\1"+
    "\1\2\4\1\3\2\2\1\11\0\300\1\47\2\25\0\4\2\u0116\1"+
    "\2\0\6\1\2\0\46\1\2\0\6\1\2\0\10\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\37\1\2\0\65\1\1\0\7\1"+
    "\1\0\1\1\3\0\3\1\1\0\7\1\3\0\4\1\2\0\6\1"+
    "\4\0\15\1\5\0\3\1\1\0\7\1\16\0\5\2\32\0\5\2"+
    "\20\0\2\1\23\0\1\1\13\0\5\2\5\0\6\2\1\0\1\1"+
    "\15\0\1\1\20\0\15\1\3\0\33\1\25\0\15\2\4\0\1\2"+
    "\3\0\14\2\21\0\1\1\4\0\1\1\2\0\12\1\1\0\1\1"+
    "\3\0\5\1\6\0\1\1\1\0\1\1\1\0\1\1\1\0\4\1"+
    "\1\0\13\1\2\0\4\1\5\0\5\1\4\0\1\1\21\0\51\1"+
    "\u0a77\0\57\1\1\0\57\1\1\0\205\1\6\0\4\1\3\2\2\1"+
    "\14\0\46\1\1\0\1\1\5\0\1\1\2\0\70\1\7\0\1\1"+
    "\17\0\1\2\27\1\11\0\7\1\1\0\7\1\1\0\7\1\1\0"+
    "\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0"+
    "\40\2\57\0\1\1\u01d5\0\3\1\31\0\11\1\6\2\1\0\5\1"+
    "\2\0\5\1\4\0\126\1\2\0\2\2\2\0\3\1\1\0\132\1"+
    "\1\0\4\1\5\0\51\1\3\0\136\1\21\0\33\1\65\0\20\1"+
    "\u0200\0\u19b6\1\112\0\u51cd\1\63\0\u048d\1\103\0\56\1\2\0\u010d\1"+
    "\3\0\20\1\12\2\2\1\24\0\57\1\1\2\4\0\12\2\1\0"+
    "\31\1\7\0\1\2\120\1\2\2\45\0\11\1\2\0\147\1\2\0"+
    "\4\1\1\0\4\1\14\0\13\1\115\0\12\1\1\2\3\1\1\2"+
    "\4\1\1\2\27\1\5\2\20\0\1\1\7\0\64\1\14\0\2\2"+
    "\62\1\21\2\13\0\12\2\6\0\22\2\6\1\3\0\1\1\4\0"+
    "\12\2\34\1\10\2\2\0\27\1\15\2\14\0\35\1\3\0\4\2"+
    "\57\1\16\2\16\0\1\1\12\2\46\0\51\1\16\2\11\0\3\1"+
    "\1\2\10\1\2\2\2\0\12\2\6\0\27\1\3\0\1\1\1\2"+
    "\4\0\60\1\1\2\1\1\3\2\2\1\2\2\5\1\2\2\1\1"+
    "\1\2\1\1\30\0\3\1\2\0\13\1\5\2\2\0\3\1\2\2"+
    "\12\0\6\1\2\0\6\1\2\0\6\1\11\0\7\1\1\0\7\1"+
    "\221\0\43\1\10\2\1\0\2\2\2\0\12\2\6\0\u2ba4\1\14\0"+
    "\27\1\4\0\61\1\u2104\0\u016e\1\2\0\152\1\46\0\7\1\14\0"+
    "\5\1\5\0\1\1\1\2\12\1\1\0\15\1\1\0\5\1\1\0"+
    "\1\1\1\0\2\1\1\0\2\1\1\0\154\1\41\0\u016b\1\22\0"+
    "\100\1\2\0\66\1\50\0\15\1\3\0\20\2\20\0\7\2\14\0"+
    "\2\1\30\0\3\1\31\0\1\1\6\0\5\1\1\0\207\1\2\0"+
    "\1\2\4\0\1\1\13\0\12\2\7\0\32\1\4\0\1\1\1\0"+
    "\32\1\13\0\131\1\3\0\6\1\2\0\6\1\2\0\6\1\2\0"+
    "\3\1\3\0\2\1\3\0\2\1\22\0\3\2\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = yy_unpack_cmap(yycmap_packed);


  /** 
   * Translates a state to a row index in the transition table (packed version)
   */
  final private static String yy_rowMap_packed = 
    "\0\0\0\67\0\156\0\245\0\334\0\67\0\67\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\u04f1\0\67\0\67\0\u0528\0\u055f\0\u0596"+
    "\0\u05cd\0\u0604\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\67\0\67\0\u074e"+
    "\0\156\0\u0785\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63"+
    "\0\u04ba\0\67\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\u0c76\0\u0cad\0\156"+
    "\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3"+
    "\0\156\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2"+
    "\0\156\0\156\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\156\0\156\0\u120c"+
    "\0\156\0\u1243\0\u127a\0\u12b1\0\156\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4"+
    "\0\u13fb\0\u1432\0\156\0\156\0\u1469\0\156\0\u14a0\0\156\0\u14d7\0\u150e"+
    "\0\u1545\0\156\0\156\0\u157c\0\156\0\156\0\156\0\156\0\u15b3\0\156"+
    "\0\156";

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int [] yy_rowMap = yy_unpack_rowMap(yy_rowMap_packed);


  /** 
   * Unpacks the compressed row translation table.
   *
   * @param packed   the packed row translation table
   * @return         the unpacked row translation table
   */
  private static int [] yy_unpack_rowMap(String packed) {
    int [] map = new int[302];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 302) {
      int high = ((int) packed.charAt(i++)) << 16;
      map[j++] = high | packed.charAt(i++);
    }
    return map;
  }
  /** 
   * The packed transition table of the DFA (part 0)
   */
  private static final String yy_packed0 = 
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\6\1\12\1\3\1\13\1\14\2\3\1\15"+
    "\1\16\2\3\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\3\1\26\1\27\2\3\1\30\1\31\1\2"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\70\0\2\3\3\0\2\3"+
    "\2\0\27\3\31\0\1\56\1\57\53\0\1\60\66\0"+
    "\1\61\14\0\2\10\64\0\1\6\62\0\2\3\3\0"+
    "\2\3\2\0\1\3\1\62\13\3\1\63\11\3\27\0"+
    "\2\3\3\0\2\3\2\0\25\3\1\64\1\3\27\0"+
    "\2\3\3\0\2\3\2\0\4\3\1\65\1\66\2\3"+
    "\1\67\16\3\27\0\2\3\3\0\2\3\2\0\14\3"+
    "\1\70\12\3\27\0\2\3\3\0\2\3\2\0\10\3"+
    "\1\71\3\3\1\72\12\3\27\0\2\3\3\0\2\3"+
    "\2\0\6\3\1\73\20\3\27\0\2\3\3\0\2\3"+
    "\2\0\10\3\1\74\16\3\27\0\2\3\3\0\2\3"+
    "\2\0\13\3\1\75\13\3\27\0\2\3\3\0\2\3"+
    "\2\0\10\3\1\76\2\3\1\77\13\3\27\0\2\3"+
    "\3\0\2\3\2\0\10\3\1\100\16\3\27\0\2\3"+
    "\3\0\2\3\2\0\2\3\1\101\1\3\1\102\15\3"+
    "\1\103\4\3\27\0\2\3\3\0\2\3\2\0\10\3"+
    "\1\104\16\3\27\0\2\3\3\0\2\3\2\0\4\3"+
    "\1\105\22\3\27\0\2\3\3\0\2\3\2\0\6\3"+
    "\1\106\20\3\27\0\2\3\3\0\2\3\2\0\27\3"+
    "\1\107\25\0\41\107\1\110\1\111\24\107\1\0\1\112"+
    "\3\0\1\113\2\0\1\114\1\113\27\112\105\0\1\115"+
    "\1\116\66\0\1\117\66\0\1\120\1\121\67\0\1\122"+
    "\67\0\1\123\63\0\1\124\66\0\1\125\66\0\1\126"+
    "\6\0\5\56\1\127\2\56\1\130\56\56\4\57\1\131"+
    "\62\57\1\0\2\3\3\0\2\3\2\0\2\3\1\132"+
    "\24\3\27\0\2\3\3\0\2\3\2\0\23\3\1\133"+
    "\3\3\27\0\2\3\3\0\2\3\2\0\5\3\1\134"+
    "\21\3\27\0\2\3\3\0\2\3\2\0\17\3\1\135"+
    "\7\3\27\0\2\3\3\0\2\3\2\0\1\3\1\136"+
    "\25\3\27\0\2\3\3\0\2\3\2\0\2\3\1\137"+
    "\24\3\27\0\2\3\3\0\2\3\2\0\11\3\1\140"+
    "\15\3\27\0\2\3\3\0\2\3\2\0\15\3\1\141"+
    "\11\3\27\0\2\3\3\0\2\3\2\0\14\3\1\142"+
    "\12\3\27\0\2\3\3\0\2\3\2\0\1\3\1\143"+
    "\25\3\27\0\2\3\3\0\2\3\2\0\17\3\1\144"+
    "\7\3\27\0\2\3\3\0\2\3\2\0\6\3\1\145"+
    "\20\3\27\0\2\3\3\0\2\3\2\0\10\3\1\146"+
    "\16\3\27\0\2\3\3\0\2\3\2\0\2\3\1\147"+
    "\24\3\27\0\2\3\3\0\2\3\2\0\6\3\1\150"+
    "\20\3\27\0\2\3\3\0\2\3\2\0\10\3\1\151"+
    "\16\3\27\0\2\3\3\0\2\3\2\0\1\152\26\3"+
    "\27\0\2\3\3\0\2\3\2\0\1\153\26\3\27\0"+
    "\2\3\3\0\2\3\2\0\1\154\26\3\27\0\2\3"+
    "\3\0\2\3\2\0\5\3\1\155\21\3\26\0\5\107"+
    "\1\0\61\107\1\0\2\112\3\0\2\112\2\0\27\112"+
    "\27\0\1\112\10\0\27\112\27\0\1\112\3\0\1\113"+
    "\4\0\27\112\33\0\1\127\61\0\3\57\1\127\1\131"+
    "\62\57\1\0\2\3\3\0\2\3\2\0\14\3\1\156"+
    "\12\3\27\0\2\3\3\0\2\3\2\0\6\3\1\157"+
    "\20\3\27\0\2\3\3\0\2\3\2\0\14\3\1\160"+
    "\12\3\27\0\2\3\3\0\2\3\2\0\2\3\1\161"+
    "\24\3\27\0\2\3\3\0\2\3\2\0\11\3\1\162"+
    "\15\3\27\0\2\3\3\0\2\3\2\0\12\3\1\163"+
    "\14\3\27\0\2\3\3\0\2\3\2\0\5\3\1\164"+
    "\21\3\27\0\2\3\3\0\2\3\2\0\5\3\1\165"+
    "\21\3\27\0\2\3\3\0\2\3\2\0\16\3\1\166"+
    "\10\3\27\0\2\3\3\0\2\3\2\0\14\3\1\167"+
    "\12\3\27\0\2\3\3\0\2\3\2\0\5\3\1\170"+
    "\21\3\27\0\2\3\3\0\2\3\2\0\10\3\1\171"+
    "\16\3\27\0\2\3\3\0\2\3\2\0\11\3\1\172"+
    "\15\3\27\0\2\3\3\0\2\3\2\0\6\3\1\173"+
    "\20\3\27\0\2\3\3\0\2\3\2\0\2\3\1\174"+
    "\24\3\27\0\2\3\3\0\2\3\2\0\7\3\1\175"+
    "\17\3\27\0\2\3\3\0\2\3\2\0\13\3\1\176"+
    "\13\3\27\0\2\3\3\0\2\3\2\0\16\3\1\177"+
    "\10\3\27\0\2\3\3\0\2\3\2\0\7\3\1\200"+
    "\17\3\27\0\2\3\3\0\2\3\2\0\1\201\26\3"+
    "\27\0\2\3\3\0\2\3\2\0\6\3\1\202\20\3"+
    "\27\0\2\3\3\0\2\3\2\0\13\3\1\203\13\3"+
    "\27\0\2\3\3\0\2\3\2\0\11\3\1\204\15\3"+
    "\27\0\2\3\3\0\2\3\2\0\21\3\1\205\5\3"+
    "\27\0\2\3\3\0\2\3\2\0\2\3\1\206\24\3"+
    "\27\0\2\3\3\0\2\3\2\0\3\3\1\207\23\3"+
    "\27\0\2\3\3\0\2\3\2\0\2\3\1\210\24\3"+
    "\27\0\2\3\3\0\2\3\2\0\3\3\1\211\23\3"+
    "\27\0\2\3\3\0\2\3\2\0\14\3\1\212\12\3"+
    "\27\0\2\3\3\0\2\3\2\0\24\3\1\213\2\3"+
    "\27\0\2\3\3\0\2\3\2\0\14\3\1\214\12\3"+
    "\27\0\2\3\3\0\2\3\2\0\1\3\1\215\25\3"+
    "\27\0\2\3\3\0\2\3\2\0\1\3\1\216\25\3"+
    "\27\0\2\3\3\0\2\3\2\0\14\3\1\217\12\3"+
    "\27\0\2\3\3\0\2\3\2\0\13\3\1\220\13\3"+
    "\27\0\2\3\3\0\2\3\2\0\2\3\1\221\24\3"+
    "\27\0\2\3\3\0\2\3\2\0\4\3\1\222\22\3"+
    "\27\0\2\3\3\0\2\3\2\0\5\3\1\223\21\3"+
    "\27\0\2\3\3\0\2\3\2\0\15\3\1\224\11\3"+
    "\27\0\2\3\3\0\2\3\2\0\11\3\1\225\15\3"+
    "\27\0\2\3\3\0\2\3\2\0\2\3\1\226\24\3"+
    "\27\0\2\3\3\0\2\3\2\0\14\3\1\227\12\3"+
    "\26\0";

  /** 
   * The transition table of the DFA
   */
  private static final int yytrans [] = yy_unpack();


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_ILLEGAL_STATE = 1;
  private static final int YY_NO_MATCH = 2;
  private static final int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final byte YY_ATTRIBUTE[] = {
     0,  9,  1,  1,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  9, 
     9,  9,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  9, 
     9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  9,  0,  1,  0,  0,  9,  9,  9,  9, 
     9,  9,  9,  9,  9,  9,  9,  1,  0,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  private boolean reportComments=false;
  private Parser parser;
  public Lexer(java.io.InputStream in, ComplexSymbolFactory sf) {
    this(in,sf,false);
  }
  public void setParser(Parser parser){
  	this.parser=parser;
  }
  public Lexer(java.io.InputStream in, ComplexSymbolFactory sf, boolean reportComments) {
    this(new java.io.InputStreamReader(in));
    symbolFactory = sf;
    this.reportComments = reportComments;
  }
    ComplexSymbolFactory symbolFactory;

  private Symbol symbol(String name, int sym) {
    return symbolFactory.newSymbol(name, sym, new ExtendedLocation(yyline+1,yycolumn+1,yychar), new ExtendedLocation(yyline+1,yycolumn+yylength(),yychar+yylength()));
  }
  
  private Symbol symbol(String name, int sym, Terminal val) {
      ExtendedLocation left = new ExtendedLocation(yyline+1,yycolumn+1,yychar);
      ExtendedLocation right=	  new ExtendedLocation(yyline+1,yycolumn+yylength(), yychar+yylength());
      val.putAnnotation("__location_left", left);
      val.putAnnotation("__location_right", right);
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }       
  
  private void error(String message) {
    System.err.println("Error at line "+(yyline+1)+", column "+(yycolumn+1)+" : "+message);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[5610];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2256) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 40: 
          {  return symbol("Address-Of operator",ADDOFOP);  }
        case 152: break;
        case 100: 
          {  return symbol("for",  FOR);  }
        case 153: break;
        case 2: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 49: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 90: 
        case 91: 
        case 92: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 97: 
        case 98: 
        case 99: 
        case 101: 
        case 102: 
        case 103: 
        case 104: 
        case 105: 
        case 106: 
        case 107: 
        case 108: 
        case 109: 
        case 112: 
        case 113: 
        case 114: 
        case 115: 
        case 116: 
        case 119: 
        case 121: 
        case 122: 
        case 123: 
        case 125: 
        case 126: 
        case 127: 
        case 128: 
        case 129: 
        case 130: 
        case 131: 
        case 134: 
        case 136: 
        case 138: 
        case 139: 
        case 140: 
        case 143: 
        case 148: 
          {  
					if (parser.sym.isTypename(yytext()))
						return symbol("Type-Name["+yytext()+"]",TYPE_NAME, new Terminal(parser.sym.getType(yytext()))); 
					return symbol("Identifier",IDENT, new Terminal<String>(yytext())); 
				   }
        case 154: break;
        case 56: 
          {  return symbol("do",   DO);  }
        case 155: break;
        case 118: 
          {  return symbol("else",  ELSE);  }
        case 156: break;
        case 25: 
          {  return symbol("Comma",COMMA);  }
        case 157: break;
        case 26: 
          {  return symbol("Hash", HASH);  }
        case 158: break;
        case 84: 
          {  return symbol("Less or equals operator",LEQ);  }
        case 159: break;
        case 30: 
          {  return symbol("Right paranthesis",RPAR);  }
        case 160: break;
        case 29: 
          {  return symbol("Left paranthesis",LPAR);  }
        case 161: break;
        case 5: 
        case 8: 
          {  /* ignore */ yylength();  }
        case 162: break;
        case 6: 
        case 7: 
          {  return symbol("Integer Constant", INTCONST, new Terminal<Integer>(Integer.parseInt(yytext())));  }
        case 163: break;
        case 145: 
          {  return symbol("switch",  SWITCH);  }
        case 164: break;
        case 137: 
          {  return symbol("while",  WHILE);  }
        case 165: break;
        case 71: 
          {  return symbol("string literal["+yytext()+"]",STRING_LITERAL, new Terminal<String>(yytext().substring(1,yytext().length()-1)));  }
        case 166: break;
        case 144: 
          {  return symbol("struct",  STRUCT);  }
        case 167: break;
        case 27: 
          {  return symbol("Left Bracket",BEGIN);  }
        case 168: break;
        case 44: 
          {  return symbol("Not operator",NOT);  }
        case 169: break;
        case 32: 
          {  return symbol("Right square bracket",RSQ);  }
        case 170: break;
        case 31: 
          {  return symbol("Left square bracket",LSQ);  }
        case 171: break;
        case 4: 
          {  return symbol("Times operator",MULOP);  }
        case 172: break;
        case 37: 
          {  return symbol("Plus operator",ADDOP);  }
        case 173: break;
        case 39: 
          {  return symbol("Minus operator",SUBOP);  }
        case 174: break;
        case 43: 
          {  return symbol("Less operator",LT);  }
        case 175: break;
        case 146: 
          {  return symbol("pragma",  PRAGMA);  }
        case 176: break;
        case 132: 
          {  return symbol("break",   BREAK);  }
        case 177: break;
        case 83: 
          {  return symbol("Greater or equals operator",GEQ);  }
        case 178: break;
        case 82: 
          {  return symbol("Or operator",OR);  }
        case 179: break;
        case 85: 
          {  return symbol("Not equals operator",NEQ);  }
        case 180: break;
        case 147: 
          {  return symbol("typedef", TYPEDEF);  }
        case 181: break;
        case 142: 
          {  return symbol("double",  DOUBLE);  }
        case 182: break;
        case 124: 
          {  return symbol("void",    VOID );  }
        case 183: break;
        case 150: 
          {  return symbol("continue",CONTINUE);  }
        case 184: break;
        case 35: 
          {  return symbol("Question mark",QUESTIONMARK);  }
        case 185: break;
        case 73: 
          {  return symbol("Selector",SELECTOR,new Terminal<String>(yytext().substring(1).trim()));  }
        case 186: break;
        case 76: 
          {  return symbol("Increment",INCOP);  }
        case 187: break;
        case 133: 
          {  return symbol("float",   FLOAT);  }
        case 188: break;
        case 117: 
          {  return symbol("long",    LONG);  }
        case 189: break;
        case 1: 
        case 24: 
        case 34: 
        case 41: 
          {   /* throw new Error("Illegal character <"+ yytext()+">");*/
		    return symbol("Illegal character (sequence): \""+ yytext()+"\"",ILLEGAL);
                   }
        case 190: break;
        case 50: 
          {  return symbol("if",  IF);  }
        case 191: break;
        case 89: 
          {  return symbol("int",     INT);  }
        case 192: break;
        case 135: 
          {  return symbol("short",   SHORT);  }
        case 193: break;
        case 120: 
          {  return symbol("goto",    GOTO);  }
        case 194: break;
        case 28: 
          {  return symbol("Right Bracket",END);  }
        case 195: break;
        case 149: 
          {  return symbol("default", DEFAULT);  }
        case 196: break;
        case 141: 
          {  return symbol("return",  RETURN);  }
        case 197: break;
        case 33: 
          {  return symbol("Semi colon",SEMI);  }
        case 198: break;
        case 38: 
          {  return symbol("Assignment operator",ASSIGN);  }
        case 199: break;
        case 80: 
          {  return symbol("Decrement",DECOP);  }
        case 200: break;
        case 81: 
          {  return symbol("And operator",AND);  }
        case 201: break;
        case 3: 
          {  return symbol("Divide operator",DIVOP);  }
        case 202: break;
        case 111: 
          {  return symbol("case",    CASE);  }
        case 203: break;
        case 110: 
          {  return symbol("char",    CHAR);  }
        case 204: break;
        case 86: 
        case 87: 
          {  if (reportComments) return symbol("comment",COMMENT); else yylength();  }
        case 205: break;
        case 42: 
          {  return symbol("Greater operator",GT);  }
        case 206: break;
        case 78: 
          {  return symbol("Equals operator",EQ);  }
        case 207: break;
        case 47: 
          {  return symbol("DIVEQ operator",DIVEQ);  }
        case 208: break;
        case 48: 
          {  return symbol("MULEQ operator",MULEQ);  }
        case 209: break;
        case 77: 
          {  return symbol("PLUSEQ operator", PLUSEQ);  }
        case 210: break;
        case 79: 
          {  return symbol("MINUSEQ operator", MINUSEQ);  }
        case 211: break;
        case 36: 
          {  return symbol("COLON operator", COLON);  }
        case 212: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {      return symbolFactory.newSymbol("EOF", EOF, new ExtendedLocation(yyline+1,yycolumn+1,yychar), new ExtendedLocation(yyline+1,yycolumn+1,yychar+1));
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] class_fields = sym.class.getFields();
      for (int i = 0; i < class_fields.length; i++) {
        if (class_fields[i].getInt(null) == token) {
          return class_fields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          scanner = new Lexer( new java.io.FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
