
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package petter.simplec;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 47;
  public static final int STRING_LITERAL = 62;
  public static final int SHORT = 8;
  public static final int CHAR = 4;
  public static final int SELECTOR = 61;
  public static final int COMMENT = 58;
  public static final int QUESTIONMARK = 35;
  public static final int CASE = 21;
  public static final int DOUBLE = 5;
  public static final int SEMI = 56;
  public static final int HASH = 16;
  public static final int CONTINUE = 18;
  public static final int TYPE_NAME = 10;
  public static final int INT = 2;
  public static final int FOR = 14;
  public static final int LSQ = 32;
  public static final int AND = 49;
  public static final int NOT = 42;
  public static final int LT = 53;
  public static final int RPAR = 31;
  public static final int DECOP = 37;
  public static final int ADDOFOP = 34;
  public static final int INTCONST = 59;
  public static final int OR = 48;
  public static final int COMMA = 26;
  public static final int MULOP = 40;
  public static final int BEGIN = 28;
  public static final int GEQ = 50;
  public static final int PLUSEQ = 44;
  public static final int MINUSEQ = 45;
  public static final int TYPEDEF = 11;
  public static final int ASSIGN = 55;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int PRAGMA = 15;
  public static final int error = 1;
  public static final int RSQ = 33;
  public static final int NEQ = 52;
  public static final int IDENT = 60;
  public static final int BREAK = 17;
  public static final int VOID = 3;
  public static final int EQ = 43;
  public static final int ADDOP = 38;
  public static final int MULEQ = 46;
  public static final int SWITCH = 22;
  public static final int INCOP = 36;
  public static final int COLON = 27;
  public static final int ILLEGAL = 57;
  public static final int ELSE = 25;
  public static final int GOTO = 19;
  public static final int WHILE = 23;
  public static final int DIVOP = 41;
  public static final int DEFAULT = 20;
  public static final int FLOAT = 6;
  public static final int LEQ = 51;
  public static final int END = 29;
  public static final int LONG = 7;
  public static final int LPAR = 30;
  public static final int SUBOP = 39;
  public static final int STRUCT = 9;
  public static final int GT = 54;
  public static final int DO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "VOID",
  "CHAR",
  "DOUBLE",
  "FLOAT",
  "LONG",
  "SHORT",
  "STRUCT",
  "TYPE_NAME",
  "TYPEDEF",
  "RETURN",
  "DO",
  "FOR",
  "PRAGMA",
  "HASH",
  "BREAK",
  "CONTINUE",
  "GOTO",
  "DEFAULT",
  "CASE",
  "SWITCH",
  "WHILE",
  "IF",
  "ELSE",
  "COMMA",
  "COLON",
  "BEGIN",
  "END",
  "LPAR",
  "RPAR",
  "LSQ",
  "RSQ",
  "ADDOFOP",
  "QUESTIONMARK",
  "INCOP",
  "DECOP",
  "ADDOP",
  "SUBOP",
  "MULOP",
  "DIVOP",
  "NOT",
  "EQ",
  "PLUSEQ",
  "MINUSEQ",
  "MULEQ",
  "DIVEQ",
  "OR",
  "AND",
  "GEQ",
  "LEQ",
  "NEQ",
  "LT",
  "GT",
  "ASSIGN",
  "SEMI",
  "ILLEGAL",
  "COMMENT",
  "INTCONST",
  "IDENT",
  "SELECTOR",
  "STRING_LITERAL"
  };
}

